name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - name: Install gettext, intltool and jq
      run: |
        sudo apt-get update
        sudo apt-get install gettext intltool jq

    - run: npm ci
    - run: npm run lint
    - run: make zip-file
    - uses: actions/upload-artifact@v4
      with:
        name: EasyScreenCast
        path: EasyScreenCast_*.zip
